version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build
      - run:
          name: Run HTML Proofer
          command: bundle exec htmlproofer --disable-external _site


workflows:
  version: 2
  commit:
    jobs:
      - test
